/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiukun_bspatch_BsPatchUtils */

#ifndef _Included_com_xiukun_bspatch_BsPatchUtils
#define _Included_com_xiukun_bspatch_BsPatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiukun_bspatch_BsPatchUtils
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xiukun_bspatch_BsPatchUtils_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
